import { LevelConfig, PaperSkin } from '../types.ts';

export const LEVELS: LevelConfig[] = [
  {
    id: 'cubicle',
    name: 'Small Office',
    subtitle: 'Classic desk distance with a breezy office fan',
    targetZ: 100,
    binScale: 1.0,
    minWind: 1,
    maxWind: 6,
    wallColorTop: '#1e293b',
    wallColorBottom: '#334155',
    floorColorTop: '#0f172a',
    floorColorBottom: '#020617',
    floorLineYRatio: 0.64,
    binType: 'mesh',
    fanType: 'desk',
    ambientDwellText: 'Standard Office · Mild AC Draft',
  },
  {
    id: 'breakroom',
    name: 'Break Room',
    subtitle: 'Short distance, larger green recycling basket',
    targetZ: 85,
    binScale: 1.15,
    minWind: 2,
    maxWind: 7,
    wallColorTop: '#292524',
    wallColorBottom: '#44403c',
    floorColorTop: '#1c1917',
    floorColorBottom: '#0c0a09',
    floorLineYRatio: 0.62,
    binType: 'recycling',
    fanType: 'desk',
    ambientDwellText: 'Kitchen Refrigerator Venting',
  },
  {
    id: 'warehouse',
    name: 'The Warehouse',
    subtitle: 'Deep distance, heavy industrial floor fan gusts',
    targetZ: 130,
    binScale: 0.95,
    minWind: 4,
    maxWind: 13,
    wallColorTop: '#172554',
    wallColorBottom: '#1e3a8a',
    floorColorTop: '#0b1329',
    floorColorBottom: '#020617',
    floorLineYRatio: 0.66,
    binType: 'plastic',
    fanType: 'industrial',
    ambientDwellText: 'High Bay Ceiling · Heavy Industrial Draft',
  },
  {
    id: 'airport',
    name: 'Airport Terminal',
    subtitle: 'Long distance crosswinds, polished stainless steel',
    targetZ: 145,
    binScale: 0.9,
    minWind: 5,
    maxWind: 16,
    wallColorTop: '#111827',
    wallColorBottom: '#1f2937',
    floorColorTop: '#090d16',
    floorColorBottom: '#030712',
    floorLineYRatio: 0.68,
    binType: 'metal',
    fanType: 'retro',
    ambientDwellText: 'Gate 42 · Terminal AC Blast',
  },
  {
    id: 'executive',
    name: 'Executive Suite',
    subtitle: 'High stakes penthouse with fine wood finishes',
    targetZ: 110,
    binScale: 1.05,
    minWind: 2,
    maxWind: 10,
    wallColorTop: '#3b0764',
    wallColorBottom: '#581c87',
    floorColorTop: '#1e1b4b',
    floorColorBottom: '#090514',
    floorLineYRatio: 0.63,
    binType: 'wood',
    fanType: 'desk',
    ambientDwellText: '54th Floor Corner Office Breeze',
  },
];

export const PAPER_SKINS: PaperSkin[] = [
  {
    id: 'classic',
    name: 'Office Paper',
    description: 'Crisp crumpled white memo sheet.',
    type: 'classic',
    primaryColor: '#ffffff',
    secondaryColor: '#e2e8f0',
    wrinkleColor: '#94a3b8',
    unlockedByDefault: true,
    unlockStreakRequirement: 0,
  },
  {
    id: 'sticky',
    name: 'Sticky Note',
    description: 'Vibrant neon yellow office memo.',
    type: 'sticky',
    primaryColor: '#fef08a',
    secondaryColor: '#fde047',
    wrinkleColor: '#ca8a04',
    unlockedByDefault: true,
    unlockStreakRequirement: 0,
  },
  {
    id: 'dollar',
    name: 'Dollar Bill',
    description: 'High roller crumpled federal banknote.',
    type: 'dollar',
    primaryColor: '#86efac',
    secondaryColor: '#4ade80',
    wrinkleColor: '#166534',
    unlockedByDefault: false,
    unlockStreakRequirement: 5,
  },
  {
    id: 'foil',
    name: 'Aluminum Foil',
    description: 'Shiny metallic reflection and crisp clinking.',
    type: 'foil',
    primaryColor: '#f8fafc',
    secondaryColor: '#cbd5e1',
    wrinkleColor: '#64748b',
    metallic: true,
    unlockedByDefault: false,
    unlockStreakRequirement: 10,
  },
  {
    id: 'crimson',
    name: 'Crimson Memo',
    description: 'Urgent red executive confidential note.',
    type: 'crimson',
    primaryColor: '#fca5a5',
    secondaryColor: '#f87171',
    wrinkleColor: '#991b1b',
    unlockedByDefault: false,
    unlockStreakRequirement: 15,
  },
  {
    id: 'gold',
    name: 'Golden Parchment',
    description: 'Pure 24k gold leaf ball for toss royalty.',
    type: 'classic',
    primaryColor: '#fef08a',
    secondaryColor: '#eab308',
    wrinkleColor: '#a16207',
    metallic: true,
    glow: true,
    unlockedByDefault: false,
    unlockStreakRequirement: 25,
  },
];
